### ISSUE TITLE
There is an error in the file 'build_visgeno_imdb.ipynb'

### ISSUE THREAD

**Issue by kylemin** [ronghanghu/cmn#1]
I tried to create my own imdb using `build_visgeno_imdb.ipynb`, but an error occurs.
It says that `rel_data` of the following lines doesn't exist. Is it `relationships`?

<pre>
rel_data_trn = [rel for rel in rel_data if rel['image_id'] in splits['train']]
rel_data_val = [rel for rel in rel_data if rel['image_id'] in splits['val']]
rel_data_tst = [rel for rel in rel_data if rel['image_id'] in splits['test']]
</pre>

If I change this to `relationships`, then another error occurs like the following.

<pre>
Loading ROI data from file...Done.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/mnt/brain1/scratch/kylemin/anaconda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/mnt/brain1/scratch/kylemin/anaconda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/brain1/scratch/kylemin/object_detection/cmn/util/visgeno_rel_train/rel_data_reader.py", line 28, in run_prefetch
    vocab_dict, T, max_bbox_num, max_rel_num)
  File "/mnt/brain1/scratch/kylemin/object_detection/cmn/util/visgeno_rel_train/prepare_batch.py", line 12, in load_one_batch
    im_path = iminfo['im_path']
KeyError: 'im_path'
</pre>

I think that it is needed to save an image path in the `build_visgeno_imdb.ipynb` file.
Could you look into this error?
Thank you.

**Comment by kylemin** [comment]
I've just resolved this.

So, `rel_data` should be replaced into `imdb`, not `relationships`.
